meta_product_name: "Happy"
meta_title: "Happy - Better moods for everyone"
meta_description: "Track your moods easily and better feelings everyday"
meta_image: "logo.png" # should exist in `app/assets/images/`
