meta_product_name: "Happy"
meta_title: "Happy - Easy mood tracking app for everyone"
meta_description: "Keeping track of your mood and activity over time. Find out which activity makes you happiest."
meta_image: "logo-title.png" # should exist in `app/assets/images/`
